#retaguarda
retaguarda_nome: RETAGUARDA -
retaguarda_server_local: Z:\\
retaguarda_hd_local: C:\\Users\\EXPECTRO\\Documentos\\teste

#kw
kw_nome: SERVIDOR KW -
kw_server_local: Y:\\backup
kw_hd_local: C:\\Users\\EXPECTRO\\Documentos\\teste