#NFCERESP
nome_nfceresp: NFCERESP Nome_da_empresa - 
servidor_nfceresp: TO DO #indique a localizaçãoda pasta no servidor
hd_nfceresp: TO DO #coloque aqui o caminho para seu hd/pendrive ou pasta
filePath_nfceresp: TO DO #mesma pasta anterior
fileUpload_nfceresp: TO DO #mesma pasta anterior
link_drive_nfceresp: TO DO #id da pasta no google_drive
  #NFCEPROC
nome_nfceproc: NFCEPROC Nome_da_empresa - 
servidor_nfceproc: TO DO #indique a localizaçãoda pasta no servidor
hd_nfceproc: TO DO #coloque aqui o caminho para seu hd/pendrive ou pasta
filePath_nfceproc: TO DO #mesma pasta anterior
fileUpload_nfceproc: TO DO #mesma pasta anterior
link_drive_nfceproc: TO DO #mesma pasta anterior

retaguarda_nome: RETAGUARDA -
retaguarda_server_local: TO DO #indique a localizaçãoda pasta no servidor
retaguarda_hd_local: TO DO #coloque aqui o caminho para seu hd/pendrive ou pasta

kw_nome: SERVIDOR KW -
kw_server_local: TO DO #indique a localizaçãoda pasta no servidor
kw_hd_local: TO DO #coloque aqui o caminho para seu hd/pendrive ou pasta
